// This is an autogenerated file (see inc-build-numbers.js)
#ifdef SIGN_ASSEMBLY
[assembly: System::Reflection::AssemblyVersion("1.0.6.129")]; //SIGNED VERSION
[assembly: System::Reflection::AssemblyFileVersion("1.0.6.129")]; //SIGNED VERSION
#else 
[assembly: System::Reflection::AssemblyVersion("1.0.5.129")]; //UNSIGNED VERSION
[assembly: System::Reflection::AssemblyFileVersion("1.0.5.129")]; //UNSIGNED VERSION
#endif 

