// This is an autogenerated file (see inc-build-numbers.js)
#ifdef SIGN_ASSEMBLY
[assembly: System::Reflection::AssemblyVersion("1.1.2.1")]; //SIGNED VERSION
[assembly: System::Reflection::AssemblyFileVersion("1.1.2.1")]; //SIGNED VERSION
#else 
[assembly: System::Reflection::AssemblyVersion("1.1.1.1")]; //UNSIGNED VERSION
[assembly: System::Reflection::AssemblyFileVersion("1.1.1.1")]; //UNSIGNED VERSION
#endif 

