//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CoApp.Toolkit.Package {
    using System.Xml.Serialization;
using System.Collections.Generic;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Package {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
        public List<Tag> Tags = new List<Tag>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Dependency", IsNullable=false)]
        public List<Dependency> Dependencies = new List<Dependency>();
        
        /// <remarks/>
        public Publisher Publisher;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public List<Contributor> Contributors = new List<Contributor>();
        
        /// <remarks/>
        public Properties Properties;
        
        /// <remarks/>
        public BindingPolicy BindingPolicy;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Url", IsNullable=false)]
        public List<Url> Urls = new List<Url>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SharedLib")]
        public List<SharedLib> SharedLib = new List<SharedLib>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AppRole")]
        public List<AppRole> AppRole = new List<AppRole>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeveloperLib")]
        public List<DeveloperLib> DeveloperLib = new List<DeveloperLib>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DriverRole")]
        public List<DriverRole> DriverRole = new List<DriverRole>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("comp", IsNullable=false)]
        public List<comp> features = new List<comp>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Arch Arch;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Platform;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proddir_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string package_guid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string product_guid;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Tag {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tag_guid;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public partial class AppFiles {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExeFile")]
        public List<ExeFile> ExeFile = new List<ExeFile>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File", typeof(File))]
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        public List<FileSysItem> Items = new List<FileSysItem>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class ExeFile : FileType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Compiler;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Arch Arch;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public enum Arch {
        
        /// <remarks/>
        x86,
        
        /// <remarks/>
        x64,
        
        /// <remarks/>
        any,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public partial class FileType : FileSysItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Src;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ext;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string component_guid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string component_id;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public partial class FileSysItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class File : FileType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Folder : FileSysItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File", typeof(File))]
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        public List<FileSysItem> Items = new List<FileSysItem>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string folder_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public partial class DriverFiles {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Driver")]
        public List<Driver> Driver = new List<Driver>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File", typeof(File))]
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        public List<FileSysItem> Items = new List<FileSysItem>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Driver : FileType {
        
        /// <remarks/>
        public File File;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public partial class Includes {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StaticLibs")]
        public List<StaticLibs> StaticLibs = new List<StaticLibs>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImportLibs")]
        public List<ImportLibs> ImportLibs = new List<ImportLibs>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Headers")]
        public List<Headers> Headers = new List<Headers>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File", typeof(File))]
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        public List<FileSysItem> Items = new List<FileSysItem>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class StaticLibs {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LibFile")]
        public List<LibFile> LibFile = new List<LibFile>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class LibFile : FileType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Compiler;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Arch Arch;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class ImportLibs {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LibFile")]
        public List<LibFile> LibFile = new List<LibFile>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Headers {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File", typeof(File))]
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        public List<FileSysItem> Items = new List<FileSysItem>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dir_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public partial class SharedLibFiles {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Assembly")]
        public List<Assembly> Assembly = new List<Assembly>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PolicyAssembly")]
        public List<PolicyAssembly> PolicyAssembly = new List<PolicyAssembly>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File", typeof(File))]
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        public List<FileSysItem> Items = new List<FileSysItem>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Assembly : FileType {
        
        /// <remarks/>
        public Manifest Manifest;
        
        /// <remarks/>
        public CatFile CatFile;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public List<File> Items = new List<File>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Arch Arch;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Manifest : FileType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class CatFile : FileType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class PolicyAssembly {
        
        /// <remarks/>
        public Manifest Manifest;
        
        /// <remarks/>
        public CatFile CatFile;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Arch Arch;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Src;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ext;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string component_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string component_guid;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public partial class Role {
        
        /// <remarks/>
        public License License;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RegistryKey", typeof(RegistryKey), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RegistryValue", typeof(RegistryValue), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RemoveRegistryKey", typeof(RemoveRegistryKey), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RemoveRegistryValue", typeof(RemoveRegistryValue), IsNullable=false)]
        public List<object> Registry = new List<object>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
        public List<Property> InstallProperties = new List<Property>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Flavor;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role_guid;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class License {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Url;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string license_guid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text = new List<string>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class RegistryKey {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Permission", typeof(Permission))]
        [System.Xml.Serialization.XmlElementAttribute("PermissionEx", typeof(PermissionEx))]
        [System.Xml.Serialization.XmlElementAttribute("RegistryKey", typeof(RegistryKey))]
        [System.Xml.Serialization.XmlElementAttribute("RegistryValue", typeof(RegistryValue))]
        public List<object> Items = new List<object>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RegistryKeyAction Action;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RegistryRootType Root;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RootSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Permission {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Domain;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string User;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType Read;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType Delete;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeleteSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType ReadPermission;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadPermissionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType ChangePermission;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChangePermissionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType TakeOwnership;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TakeOwnershipSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType ReadAttributes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadAttributesSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType WriteAttributes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WriteAttributesSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType ReadExtendedAttributes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadExtendedAttributesSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType WriteExtendedAttributes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WriteExtendedAttributesSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType Synchronize;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SynchronizeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType CreateFile;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateFileSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType CreateChild;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateChildSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType DeleteChild;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeleteChildSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType Traverse;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TraverseSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType Append;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AppendSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType Execute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExecuteSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType Write;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WriteSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType CreateSubkeys;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateSubkeysSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType EnumerateSubkeys;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumerateSubkeysSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType Notify;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotifySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType CreateLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateLinkSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType GenericAll;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenericAllSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType GenericExecute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenericExecuteSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType GenericWrite;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenericWriteSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType GenericRead;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenericReadSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public enum YesNoType {
        
        /// <remarks/>
        no,
        
        /// <remarks/>
        yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class PermissionEx {
        
        /// <remarks/>
        public Condition Condition;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sddl;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Condition {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConditionAction Action;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Level;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public enum ConditionAction {
        
        /// <remarks/>
        @default,
        
        /// <remarks/>
        enable,
        
        /// <remarks/>
        disable,
        
        /// <remarks/>
        hide,
        
        /// <remarks/>
        show,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class RegistryValue {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("MultiStringValue", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("Permission", typeof(Permission))]
        [System.Xml.Serialization.XmlElementAttribute("PermissionEx", typeof(PermissionEx))]
        public List<object> Items = new List<object>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text = new List<string>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RegistryRootType Root;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RootSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RegistryValueType Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RegistryValueAction Action;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoType KeyPath;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeyPathSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public enum RegistryRootType {
        
        /// <remarks/>
        HKMU,
        
        /// <remarks/>
        HKCR,
        
        /// <remarks/>
        HKCU,
        
        /// <remarks/>
        HKLM,
        
        /// <remarks/>
        HKU,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public enum RegistryValueType {
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        integer,
        
        /// <remarks/>
        binary,
        
        /// <remarks/>
        expandable,
        
        /// <remarks/>
        multiString,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public enum RegistryValueAction {
        
        /// <remarks/>
        append,
        
        /// <remarks/>
        prepend,
        
        /// <remarks/>
        write,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public enum RegistryKeyAction {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        createAndRemoveOnUninstall,
        
        /// <remarks/>
        none,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class RemoveRegistryKey {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RemoveRegistryKeyAction Action;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RegistryRootType Root;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RootSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public enum RemoveRegistryKeyAction {
        
        /// <remarks/>
        removeOnInstall,
        
        /// <remarks/>
        removeOnUninstall,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class RemoveRegistryValue {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RegistryRootType Root;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RootSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Property {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Link;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Target;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string prop_guid;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public partial class Contributor {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Dependency {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string package_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Arch Arch;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArchSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PublicKeyToken;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PackageType Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CommandLine;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd")]
    public enum PackageType {
        
        /// <remarks/>
        coapp,
        
        /// <remarks/>
        nuget,
        
        /// <remarks/>
        msi,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Publisher {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PublicKeyToken;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Location;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string directory_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Properties {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Icon;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime PublishDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublishDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AuthorVersion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SummaryDescription;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Location;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Feed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string feed_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class BindingPolicy {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MinimumVersion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaximumVersion;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Url {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url_guid;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class SharedLib : Role {
        
        /// <remarks/>
        public SharedLibFiles Files;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class AppRole : Role {
        
        /// <remarks/>
        public AppFiles Files;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class DeveloperLib : Role {
        
        /// <remarks/>
        public Includes Files;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class DriverRole : Role {
        
        /// <remarks/>
        public DriverFiles Files;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class comp {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string component_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Tags {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tag")]
        public List<Tag> Tag = new List<Tag>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Dependencies {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dependency")]
        public List<Dependency> Dependency = new List<Dependency>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class InstallProperties {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public List<Property> Property = new List<Property>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class StaticLib {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File", typeof(File))]
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        public List<FileSysItem> Items = new List<FileSysItem>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class ImportLib {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File", typeof(File))]
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        public List<FileSysItem> Items = new List<FileSysItem>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Registry {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistryKey", typeof(RegistryKey))]
        [System.Xml.Serialization.XmlElementAttribute("RegistryValue", typeof(RegistryValue))]
        [System.Xml.Serialization.XmlElementAttribute("RemoveRegistryKey", typeof(RemoveRegistryKey))]
        [System.Xml.Serialization.XmlElementAttribute("RemoveRegistryValue", typeof(RemoveRegistryValue))]
        public List<object> Items = new List<object>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class features {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comp")]
        public List<comp> comp = new List<comp>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class Urls {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Url")]
        public List<Url> Url = new List<Url>();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://coapp.org/ns/mkPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://coapp.org/ns/mkPackage.xsd", IsNullable=false)]
    public partial class SourceCode : Role {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("File", typeof(File), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Folder", typeof(Folder), IsNullable=false)]
        public List<FileSysItem> Files = new List<FileSysItem>();
    }
}
